# Generated by Django 3.2.6 on 2021-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_ifood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
