# Generated by Django 3.2.6 on 2021-09-30 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_ifood', '0003_pedido_valor_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 10, 26, 19, 774114)),
        ),
    ]
