# Generated by Django 3.2.6 on 2021-09-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_ifood', '0005_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 10, 27, 50, 749620)),
        ),
    ]
