# Generated by Django 3.2.6 on 2021-09-30 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_ifood', '0007_auto_20210930_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 11, 23, 58, 170746)),
        ),
    ]
